# permissions for end users to edit consulkvsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consulkvsecret-editor-role
rules:
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets/status
  verbs:
  - get
