# permissions for end users to view consulkvsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consulkvsecret-viewer-role
rules:
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets/status
  verbs:
  - get
