# permissions for end users to edit kvsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kvsecret-editor-role
rules:
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - kvsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - kvsecrets/status
  verbs:
  - get
