# permissions for end users to view kvsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kvsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: kvsecret-viewer-role
rules:
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - kvsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - kvsecrets/status
  verbs:
  - get
