# permissions for end users to view kvsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kvsecret-viewer-role
rules:
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - kvsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - kvsecrets/status
  verbs:
  - get
