---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - consul-kv.caproven.info
  resources:
  - consulkvsecrets/status
  verbs:
  - get
  - patch
  - update
