apiVersion: consul-kv.caproven.info/v1alpha1
kind: KVSecret
metadata:
  name: kvsecret-sample
spec:
  source:
    host: http://localhost
    port: 8500
    token: ""
  values:
    - sourcekey: foo
      key: foo
    - sourcekey: bar
      key: bar
    - sourcekey: bar
      key: baz
  output:
    name: foobar-secret
  refreshInterval: 10
