apiVersion: consul-kv.caproven.info/v1alpha1
kind: ConsulKVSecret
metadata:
  name: consulkvsecret-sample
spec:
  source:
    address: http://localhost:8500
    token: null
  secret:
    # immutable, defaults to metadata.name
    name: mysecretfromconsul
    data:
      - sourcekey: config/application/sas/database/databaseServerName
        # probably keep this required, 
        key: databaseServerName
