apiVersion: consul-kv.caproven.info/v1alpha1
kind: KVSecret
metadata:
  name: kvsecret-sample
spec:
  source:
    # host: http://consul-consul-server.consul.svc.cluster.local
    host: http://localhost
    port: 8500
    token: ""
  values:
    - sourcekey: myawesomekey
      # TODO required, or construct from sourcekey? review valid consul keys
      key: myawesomekey
    - sourcekey: my/application/databaseName
      key: databaseName
    - sourcekey: my/application/databaseUsername
      key: databaseUsername
    - sourcekey: my/application/databasePassword
      key: databasePassword
  output:
    # immutable, defaults to metadata.name
    name: mysecretfromconsul
  refreshInterval: 30
