apiVersion: consul-kv.caproven.info/v1alpha1
kind: ConsulKVSecret
metadata:
  name: consulkvsecret-sample
spec:
  source:
    # host: consul-consul-server.consul.svc.cluster.local
    host: localhost
    port: 8500
    token: ""
  values:
    - sourcekey: myawesomekey
      # TODO required, or construct from sourcekey? review valid consul keys
      key: myawesomekey
    - sourcekey: my/application/databaseName
      key: databaseName
    - sourcekey: my/application/databaseUsername
      key: databaseUsername
    - sourcekey: my/application/databasePassword
      key: databasePassword
  secret:
    # immutable, defaults to metadata.name
    name: mysecretfromconsul
