apiVersion: consul-kv.caproven.info/v1alpha1
kind: KVSecret
metadata:
  labels:
    app.kubernetes.io/name: kvsecret
    app.kubernetes.io/instance: kvsecret-sample
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder
  name: kvsecret-sample
spec:
  source:
    host: http://localhost
    port: 8500
    token: ""
  values:
    - sourcekey: foo
      key: foo
    - sourcekey: bar
      key: bar
    - sourcekey: bar
      key: baz
  output:
    name: foobar-secret
  refreshInterval: 10
