//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecret) DeepCopyInto(out *ConsulKVSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecret.
func (in *ConsulKVSecret) DeepCopy() *ConsulKVSecret {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsulKVSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecretList) DeepCopyInto(out *ConsulKVSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConsulKVSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecretList.
func (in *ConsulKVSecretList) DeepCopy() *ConsulKVSecretList {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConsulKVSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecretOutput) DeepCopyInto(out *ConsulKVSecretOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecretOutput.
func (in *ConsulKVSecretOutput) DeepCopy() *ConsulKVSecretOutput {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecretOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecretSource) DeepCopyInto(out *ConsulKVSecretSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecretSource.
func (in *ConsulKVSecretSource) DeepCopy() *ConsulKVSecretSource {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecretSpec) DeepCopyInto(out *ConsulKVSecretSpec) {
	*out = *in
	out.Source = in.Source
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]ConsulKVSecretValue, len(*in))
		copy(*out, *in)
	}
	out.Output = in.Output
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecretSpec.
func (in *ConsulKVSecretSpec) DeepCopy() *ConsulKVSecretSpec {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecretStatus) DeepCopyInto(out *ConsulKVSecretStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecretStatus.
func (in *ConsulKVSecretStatus) DeepCopy() *ConsulKVSecretStatus {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsulKVSecretValue) DeepCopyInto(out *ConsulKVSecretValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsulKVSecretValue.
func (in *ConsulKVSecretValue) DeepCopy() *ConsulKVSecretValue {
	if in == nil {
		return nil
	}
	out := new(ConsulKVSecretValue)
	in.DeepCopyInto(out)
	return out
}
